title: Yuerong Zhang
logo: /img/img_yz.png
description: Lecturer (Assistant Professor) in Geospatial Machine Learning
linkedin: https://www.linkedin.com/in/Yuerong Zhang
research_interests:
  - Transport resilience
  - Transport and energy
  - Geospatial Machine Learning
theme: jekyll-theme-minimal

# Add icons with hyperlinks
social_icons:
  - name: Email
    icon: /img/email_icon.png
    link: mailto:yr.zhang@ucl.ac.uk
  - name: Google Scholar
    icon: /img/google_scholar_icon.png
    link: https://scholar.google.com/citations?user=jv4nE5gAAAAJ&hl=en&oi=ao
  - name: ORCID
    icon: /img/orcid_icon.png
    link: https://orcid.org/0000-0001-7956-8640
