title: Yuerong Zhang
logo: /img/img_yz.png
description: Lecturer (Assistant Professor) in Geospatial Machine Learning
theme: jekyll-theme-minimal

# Social links with FontAwesome icons
social_links:
  - name: LinkedIn
    url: "https://www.linkedin.com/in/Yuerong Zhang"
    icon: fab fa-linkedin
  - name: Google Scholar
    url: "https://scholar.google.com/citations?user=jv4nE5gAAAAJ&hl=en&oi=ao"
    icon: fas fa-graduation-cap
  - name: ORCID
    url: "https://orcid.org/0000-0001-7956-8640"
    icon: fab fa-orcid

research_interests:
  - Transport resilience
  - Transport and energy
  - Geospatial Machine Learning

# Navigation links for the top bar
nav_links:
  - name: Publications
    url: "/publications"
  - name: Research
    url: "/research"
  - name: CV
    url: "/cv"
  - name: Contact
    url: "/contact"




