title: Yuerong Zhang
logo: /img/img_yz.png
description: Lecturer (Assistant Professor) in Geospatial Machine Learning
linkedin: https://www.linkedin.com/in/Yuerong Zhang
research_interests:
  - Transport resilience
  - Transport and energy
  - Geospatial Machine Learning
